### ISSUE TITLE
error: proc-macro derive panicked in bart_derive::parse_str

### ISSUE THREAD

**Issue by aep** [maghoff/bart#22]
tried to pass an option to a function

```
option width {{.width.to_htmode("VHT80")}}
```

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: Mismatch', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:380
   3: std::panicking::default_hook
             at libstd/panicking.rs:396
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:576
   5: std::panicking::begin_panic
             at libstd/panicking.rs:537
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:521
   7: rust_begin_unwind
             at libstd/panicking.rs:497
   8: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  11: bart_derive::parse_str
             at /home/aep/.cargo/registry/src/github.com-1ecc6299db9ec823/bart_derive-0.1.4/src/lib.rs:44
  12: bart_derive::bart_display
             at /home/aep/.cargo/registry/src/github.com-1ecc6299db9ec823/bart_derive-0.1.4/src/lib.rs:108
  13: std::panicking::try::do_call
  14: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  15: <syntax_ext::deriving::custom::ProcMacroDerive as syntax::ext::base::MultiItemModifier>::expand
  16: syntax::ext::expand::MacroExpander::expand_invoc
  17: syntax::ext::expand::MacroExpander::expand
  18: syntax::ext::expand::MacroExpander::expand_crate
  19: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}
  20: rustc_driver::driver::phase_2_configure_and_expand_inner
  21: rustc_driver::driver::compile_input
  22: rustc_driver::run_compiler

```

**Comment by maghoff** [comment]
Thanks for your interest :) Passing arguments to functions is not supported and support is not planned. 

This does not seem to be documented anywhere, sorry about that.

The error message is not nice either. Sorry about that, too. However, note that panicing is the only way for a proc_macro to signal a compile time error as far as I am aware.

When deciding the syntax for calling functions, I was a bit worried that using `()` is too evocative of normal function calls where it is possible to pass arguments, but I did not find a reasonable alternative.
